---
labels:
  - name: "type:feature"
    color: "a2eeef"
    description: "Feature request or enhancement"
  - name: "type:bug"
    color: "d73a4a"
    description: "Bug or defect"
  - name: "type:docs"
    color: "0075ca"
    description: "Documentation changes"
  - name: "type:ops"
    color: "0e8a16"
    description: "Operational, CI/CD, or infra work"
  - name: "priority:P0"
    color: "b60205"
    description: "Highest priority"
  - name: "priority:P1"
    color: "d93f0b"
    description: "High priority"
  - name: "priority:P2"
    color: "fbca04"
    description: "Normal priority"
  - name: "status:blocked"
    color: "5319e7"
    description: "Blocked by dependency or decision"
