blank_issues_enabled: false
contact_links:
  - name: Security issue
    url: https://github.com/abranch43/branchbot-deploy/security
    about: Please report security vulnerabilities privately via GitHub Security advisories.

