name: Labels Sync

on:
  push:
    branches: ["main", "feat/scaffold-initial"]
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      metadata: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Sync labels
        uses: crazy-max/ghaction-github-labeler@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          config-file: .github/labels.yml
          skip-delete: true

