name: Quality Gates

on:
  push:
  pull_request:

jobs:
  node-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Detect package.json
        id: detect
        run: |
          if [ -f package.json ]; then
            echo "present=true" >> $GITHUB_OUTPUT
          fi
      - name: No package.json found
        if: steps.detect.outputs.present != 'true'
        run: echo "No package.json found. Skipping Node checks."
      - name: Setup Node
        if: steps.detect.outputs.present == 'true'
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        if: steps.detect.outputs.present == 'true'
        run: npm ci
      - name: Run lint
        if: steps.detect.outputs.present == 'true'
        run: npm run lint
      - name: Run tests
        if: steps.detect.outputs.present == 'true'
        run: npm test
